version: "3.1"

services:
  wowjs:
    image: wowjs
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    links:
      - mongodb:mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /mongodata:/data/db
